-- AlterTable: Add expanded consultation fields
ALTER TABLE `student_data`
  ADD COLUMN `spot_esferico_od`    VARCHAR(20) NULL,
  ADD COLUMN `spot_cilindrico_od`  VARCHAR(20) NULL,
  ADD COLUMN `spot_eixo_od`        VARCHAR(20) NULL,
  ADD COLUMN `spot_eq_esferico_od` VARCHAR(20) NULL,
  ADD COLUMN `spot_dp_od`          VARCHAR(20) NULL,
  ADD COLUMN `spot_esferico_oe`    VARCHAR(20) NULL,
  ADD COLUMN `spot_cilindrico_oe`  VARCHAR(20) NULL,
  ADD COLUMN `spot_eixo_oe`        VARCHAR(20) NULL,
  ADD COLUMN `spot_eq_esferico_oe` VARCHAR(20) NULL,
  ADD COLUMN `spot_dp_oe`          VARCHAR(20) NULL,
  ADD COLUMN `spot_observacao`     TEXT NULL,
  ADD COLUMN `anamnese`            TEXT NULL,
  ADD COLUMN `ref_estatica_esferico_od`   VARCHAR(20) NULL,
  ADD COLUMN `ref_estatica_cilindrico_od` VARCHAR(20) NULL,
  ADD COLUMN `ref_estatica_eixo_od`       VARCHAR(20) NULL,
  ADD COLUMN `ref_estatica_acuidade_od`   VARCHAR(20) NULL,
  ADD COLUMN `ref_estatica_esferico_oe`   VARCHAR(20) NULL,
  ADD COLUMN `ref_estatica_cilindrico_oe` VARCHAR(20) NULL,
  ADD COLUMN `ref_estatica_eixo_oe`       VARCHAR(20) NULL,
  ADD COLUMN `ref_estatica_acuidade_oe`   VARCHAR(20) NULL,
  ADD COLUMN `biomicroscopia_od`   TEXT NULL,
  ADD COLUMN `biomicroscopia_oe`   TEXT NULL,
  ADD COLUMN `fundoscopia_od`      TEXT NULL,
  ADD COLUMN `fundoscopia_oe`      TEXT NULL,
  ADD COLUMN `motilidade_ocular`   TEXT NULL,
  ADD COLUMN `diagnostico`         TEXT NULL,
  ADD COLUMN `conduta`             TEXT NULL,
  ADD COLUMN `precisa_oculos`      VARCHAR(1) NULL,
  ADD COLUMN `acomp_ambliopia`              BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `acomp_retinoblastoma`         BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `acomp_catarata_congenita`     BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `acomp_obstrucao_lacrimais`    BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `acomp_estrabismo`             BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `acomp_glaucoma_congenito`     BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `acomp_uveites`                BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `acomp_nistagmo`               BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `acomp_miopia_progressiva`     BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `acomp_ectasias_cornea`        BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `acomp_alergias_conjuntivites` BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `acomp_baixa_visao_central`    BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `proxima_consulta_meses`       VARCHAR(10) NULL,
  ADD COLUMN `observacoes_consulta`         TEXT NULL;
